accounts/urls.py
# chat/urls.py
from django.urls import path
from . import views


urlpatterns = [
    path('signup/', views.signup_worker),
    path('signup_change/', views.signup_change),
    path('signup_company/', views.signup_company),
    path('login/', views.Login),
    path('loginexpo/', views.LoginExpo),
    path('logout/', views.Logout),
    path('reset/', views.Reset),
]

expo/urls.py
from django.contrib import admin
from django.urls import path, include
from expo import views

urlpatterns = [
    path('adminexpo/workers/', views.adminexpoworkers),
    path('adminexpo/comments/', views.adminexpocomments),
    path('adminexpo/companys/', views.adminexpocompanys),
    path('adminexpo/newcompanys/', views.adminexponewcompanys),
    path('adminexpo/charts/', views.adminexpocharts),
    path('adminexpo/save/', views.adminexposave),
    path('adminexpo/news/', views.adminexponews),
    path('adminexpo/', views.adminexpo),
    path('admin/', admin.site.urls),
    path('accounts/', include('accounts.urls')),
    path('', include('main.urls')),
    path('worker/', include('worker.urls')),
    path('forbiden/', views.forbiden),
    path('notfound/', views.notfound),
    path('servererror/', views.servererror),
    path('success/', views.success),
    path('privacy-policy/', views.privacypolicy),
    path('legal/', views.legal),
    path('termsofuse/', views.termsOfUse),
    path('confidential/', views.confidential),
    path('companys/', views.companys),
    path('company/', views.company),
    path('messages/new/', views.newmessage),
    path('messages/send/', views.messagesend),
    path('messages/', views.messages),
    path('messages/getcount', views.getcountmessage),
    path('dialogs/', views.dialogs),
    path('responses/', views.responses),
    path('responses/getcount', views.getcountresponses),
    path('responses/setResponseStatus/', views.setResponseStatus),
    path('news/save/', views.savenews),
    path('news/', views.news),
    path('jobs/save/', views.savejobs),
    path('jobs/info/', views.infojobs),
    path('jobs/saveorder/', views.saveorder),
    path('jobs/new/', views.newjobs),
    path('jobs/', views.jobs),
    path('sendsms/', views.sendsms),
    path('testtest/', views.testtest)
]

main/urls.py
from django.contrib import admin
from django.urls import path, include
from . import views
from expo.views import notfound
from django.conf.urls.static import static
from django.contrib.staticfiles.urls import staticfiles_urlpatterns
from django.conf import settings

#handler404 = notfound

urlpatterns = [
    path('', views.show),
    path('sendlink/', views.sendlink),
    path('m/servicelist/', views.jsonServicesList),
    #path('m/servicelist/save/', views.ServicesListSave),
    path('m/selectionparameters/', views.jsonSelectionParameters),
    path('m/citylist/', views.jsonCityList),
    path('m/citylistgroup/', views.jsonCityListGroup),
    path('m/countrylist/', views.jsonCountryList),
    path('m/checklogin/', views.checkLogin),
    path('m/checkserver/', views.checkServer),
    path('m/professionlist/', views.jsonProfessionList),
    path('m/fiolist/', views.jsonFioList),
    #path('m/professionlist/save/', views.ProfessionsListSave),
    path('m/professionandgroups/', views.showJson),
    path('m/companies/', views.jsonCompanyList)
]

urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)
urlpatterns += staticfiles_urlpatterns()

main/models.py
from django.core.exceptions import ObjectDoesNotExist
from django.contrib.auth.models import User
from django.db import connection, models
from django.db.models.signals import m2m_changed #, post_save
from django.db.models import Q
from django.utils import timezone
from django.dispatch import receiver
import datetime
import uuid
import base64
import random
from typing import Type
from PIL import Image
from django.conf import settings
from os import path
from expo.Balance import sendMessage
from expo.PassGen import generate_password
from expo.validate_uuid4 import validate_uuid4
import logging

logger = logging.getLogger(__name__)

class UserActivity(models.Model):

    id   = models.UUIDField(primary_key=True, default=uuid.uuid4, editable=False)
    user = models.ForeignKey(User, on_delete=models.CASCADE)
    date = models.DateField(datetime.date, default=None, null=True)

    def __str__(self):
        return str(self.user) + " - " + str(self.date)

    def setActivity(user):

        try:
            act = UserActivity.objects.get(date=datetime.datetime.now().date(), user=user)
        except Exception as e:
            act = UserActivity()
            act.user = user
            act.date = datetime.datetime.now().date()

            act.save()

class WorkGroup(models.Model):

    id      = models.UUIDField(primary_key=True, default=uuid.uuid4, editable=False)
    name = models.CharField(max_length=100)

    def __str__(self):
        return self.name

class Professions(models.Model):

    id          = models.UUIDField(primary_key=True, default=uuid.uuid4, editable=False)
    name        = models.CharField(max_length=100)
    idWorkGroup = models.ForeignKey(WorkGroup, on_delete=models.CASCADE)
    indexName   = models.CharField(max_length=100)
    workerСount = models.DecimalField("Количество рабочих", max_digits=10, decimal_places=0, default=0)

    def __str__(self):
        return self.name

    def setWorkerCount(self):

        print("Сохраняем количество по профессиям")
        cursor = connection.cursor()

        cursor.execute("SELECT main_professions.id, COUNT(main_worker.id) FROM main_professions LEFT JOIN main_worker_professions ON main_professions.id = main_worker_professions.professions_id LEFT JOIN main_worker ON main_worker.id = main_worker_professions.worker_id AND main_worker.publishdata GROUP BY main_professions.id")

        row = cursor.fetchall()

        for e in row:
            prof = Professions.objects.get(id=e[0])
            prof.workerСount = e[1]
            prof.save()

class Service(models.Model):

    id          = models.UUIDField(primary_key=True, default=uuid.uuid4, editable=False)
    name        = models.CharField(max_length=100)
    unit        = models.CharField(max_length=10)

    def __str__(self):
        return self.name

class Country(models.Model):

    id          = models.UUIDField(primary_key=True, default=uuid.uuid4, editable=False)
    name        = models.CharField(max_length=100)
    workpermit  = models.BooleanField(default=False)

    def __str__(self):
        return self.name

class Region(models.Model):

    id          = models.UUIDField(primary_key=True, default=uuid.uuid4, editable=False)
    name        = models.CharField(max_length=100)
    country     = models.ForeignKey(Country, on_delete=models.CASCADE, default='00000000000000000000000000000000')

    def __str__(self):
        return self.name

class City(models.Model):

    id          = models.UUIDField(primary_key=True, default=uuid.uuid4, editable=False)
    name        = models.CharField(max_length=100)
    indexName   = models.CharField(max_length=100)
    country     = models.ForeignKey(Country, on_delete=models.CASCADE, default='00000000000000000000000000000000')
    region      = models.ForeignKey(Region, on_delete=models.CASCADE, default='00000000000000000000000000000000')

    def __str__(self):
        return self.name

    def save(self, *args, **kwargs):
        self.indexName = self.name.upper()
        super(City, self).save(*args, **kwargs)  # Call the "real" save() method.

class WorkerAttachment(models.Model):

    id          = models.UUIDField(primary_key=True, default=uuid.uuid4, editable=False)
    file        = models.FileField(null=True, blank=True, upload_to="media/attach/", verbose_name='Изображение')
    resizeFile  = models.FileField(null=True, blank=True, upload_to="media/resizeattach/", verbose_name='Изображение')
    Description = models.CharField(max_length=200)

class Attacment(models.Model):

    id          = models.UUIDField(primary_key=True, default=uuid.uuid4, editable=False)
    path        = models.FileField(null=True, blank=True, upload_to="media/attach/", verbose_name='Изображение')
    resizePath  = models.FileField(null=True, blank=True, upload_to="media/resizeattach/", verbose_name='Изображение')
    Description = models.CharField(max_length=200)

    def savefile(base64data, src = 'attacment', resizeit=False):

        if base64data.find('base64') != -1:

            if base64data.find('image/') == -1:
                return None
            d = base64data.partition(",")

            strOne = d[2]
            strOne = b"=" + strOne.encode()

        else:
            strOne = base64data

        print('before base dir')

        BASE_DIR = path.dirname(path.dirname(path.abspath(__file__)))
        print(str(BASE_DIR))
        MEDIA_ROOT = path.join(BASE_DIR, 'media/media/')
        print(str(MEDIA_ROOT))

        directory       = str(MEDIA_ROOT)
        name            = str(uuid.uuid4()) + '.png'
        fullpath        = path.join(directory, src, name)
        attachment      = Attacment()
        print("fullpath=============================================")
        fullpath = path.join(directory, 'attach', name)
        print(fullpath)
        try:
            print('1')
            with open(fullpath, "wb") as fh:
                print('2')
                b64decode = base64.b64decode(strOne.strip())
                print('3')
                fh.write(b64decode)
                print('4')
                attachment.path = fullpath.replace(directory, '').replace('\\', '/')
                print("attachment.path=============================================")
                print(attachment.path)
            if resizeit:
                print('5')
                resizename = str(uuid.uuid4()) + '.png'
                print('6')
                fullresizepath = path.join(directory, 'resizeattach', resizename)
                print(fullresizepath)
                Attacment.scale_image(input_image_path=fullpath, output_image_path=fullresizepath)
                print('7')
                attachment.resizePath = fullresizepath.replace(directory, '').replace('\\', '/')
            attachment.save()
        except Exception as e:
            return False

        return attachment

    def scale_image(input_image_path,
                    output_image_path,
                    width=150,
                    height=150
                    ):

        original_image = Image.open(input_image_path)
        w, h = original_image.size
        if w > h:
            position = (w - h) / 2
            croped_image = original_image.crop((position, 0, w - position, h))
        elif h > w:
            position = (h - w) / 2
            croped_image = original_image.crop((0, position, w, h - position))
        else:
            croped_image = original_image

        if width and height:
            max_size = (width, height)
        elif width:
            max_size = (width, h)
        elif height:
            max_size = (w, height)
        else:
            # No width or height specified
            raise RuntimeError('Width or height required!')

        croped_image.thumbnail(max_size, Image.ANTIALIAS)
        croped_image.save(output_image_path)

        return output_image_path

    def getresizelink(attach):

        if attach.resizePath:

            if str(attach.resizePath)[0:1] =='/':
                img = str(settings.MEDIA_URL)+ str(attach.resizePath)[1:]
            else:
                img = str(settings.MEDIA_URL)+ str(attach.resizePath)

            print('-------------->'+img)

            img = img.replace('media/media/', 'media/')

            return ('https://vseexpo.ru/media'+img)
        else:
            return 'https://vseexpo.ru'+str(settings.STATIC_URL) + 'main/img/add-photo.png'

    def getlink(attach):
        if attach.path:

            if str(attach.path)[0:1] =='/':
                img = str(settings.MEDIA_URL) + str(attach.path)[1:]
            else:
                img = str(settings.MEDIA_URL) + str(attach.resizePath)

            img = img.replace('media/media/', 'media/')        

            return ('https://vseexpo.ru/media'+img)
        else:
            return 'https://vseexpo.ru'+str(settings.STATIC_URL) + 'main/img/add-photo.png'

class Worker(models.Model):

    id          = models.UUIDField(primary_key=True, default=uuid.uuid4, editable=False)
    #user_id     = models.ForeignKey(User, on_delete=models.CASCADE)
    #user_id     = models.OneToOneField(User, on_delete=models.CASCADE)
    block       = models.BooleanField(default=False) #Заблокирован
    name        = models.CharField(max_length=100, default="Не указано")
    surname     = models.CharField(max_length=100)
    nationality = models.ForeignKey(Country, on_delete=models.CASCADE, default="00000000000000000000000000000000")
    education   = models.TextField()
    lastname    = models.CharField(max_length=100)
    haveIP      = models.BooleanField(default=False)
    haveShengen = models.BooleanField(default=False)
    haveIntPass = models.BooleanField(default=False) #ЗагранПаспорт
    readytotravel = models.BooleanField(default=False) #Готов к командировкам
    haveInstrument = models.BooleanField(default=False)
    fsocheck    = models.BooleanField(default=False)
    workpermit  = models.BooleanField(default=False)

main/forms.py
from django.forms import ModelForm
from django import forms
from .models import Comments

class CommentForm(ModelForm):
    """Форма комментариев к статьям
    """
    class Meta:
        model = Comments
        fields = ('text', 'rating', 'idProf')

main/templates/accounts/email_confirm.html
{% extends "account/base.html" %}

{% load i18n %}
{% load account %}

{% block head_title %}{% trans "Confirm E-mail Address" %}{% endblock %}


{% block content %}
<h1>{% trans "Confirm E-mail Address" %}</h1>

{% if confirmation %}

{% user_display confirmation.email_address.user as user_display %}

<p>{% blocktrans with confirmation.email_address.email as email %}Please confirm that <a href="mailto:{{ email }}">{{ email }}</a> is an e-mail address for user {{ user_display }}.{% endblocktrans %}</p>

<form method="post" action="{% url 'account_confirm_email' confirmation.key %}">
{% csrf_token %}
    <button type="submit">{% trans 'Confirm' %}</button>
</form>

{% else %}

{% url 'account_email' as email_url %}

<p>{% blocktrans %}This e-mail confirmation link expired or is invalid. Please <a href="{{ email_url }}">issue a new e-mail confirmation request</a>.{% endblocktrans %}</p>

{% endif %}

{% endblock %}

main/templates/accounts/login.html
{% extends "wrapper.html" %}

{% block content %}

<div style="left: 50%; top: 50%; position: absolute; margin: -250px 0 0 -250px;">

    <div class="card" style="width: 500px; border-radius: 0px">
        <div class="card-header text-center">
            <span class="article">Вход</span>
        </div>
        <div class="card-body">
            <h5 class="card-title text-center">
                <p>Если вы не зарегистрированы на сайте, пожалуйста
                <a href="/accounts/signup/">Зарегистрируйтесь</a></p>
            </h5>
            {% include "accounts/login_form.html" %}
            <div class="text-right container-fluid">
                <a href="/accounts/reset/">Забыли пароль?</a></p>
            </div>
        </div>
    </div>

</div>



{% endblock %}

main/templates/accounts/loginExpo.html
{% extends "adminexpo/wrapper.html" %}
{% load home_extras %}
{% block content%}

    <div class="container">

        <div style="left: 50%; top: 50%; position: absolute; margin: -250px 0 0 -250px;">

            <div class="card" style="width: 500px; border-radius: 0px">
                <div class="card-header text-center">
                    <span class="article">Вход</span>
                </div>
                <div class="card-body">
                  <form action="/accounts/loginexpo/" name="loginform" method="POST" action="" id="loginform">
                        {% csrf_token %}

                        <div class="form-group row">
                            <label for="id_username" class="col col-4 col-form-label">Логин</label>
                            <div class="col col-8">
                                <input style="border-radius: 0px" name="username" type="text" class="form-control" id="id_username" placeholder="Имя входа" value="{{ username }}" required>
                                {% if errors %}
                                    {% for i in errors %}
                                        <span style="color: red; font-size: 10px">{{ i }}</span>
                                    {% endfor %}
                                {% endif %}
                            </div>
                        </div>

                        <div class="form-group row">
                            <label for="id_password" class="col-sm-4 col-form-label">Пароль</label>
                            <div class="col-sm-8">
                                <input style="border-radius: 0px" name="password" type="password" class="form-control" id="id_password" placeholder="Пароль" value="{{ password1 }}" required>
                            </div>
                        </div>

                        <div class="form-group row">
                            <div class="col col-6"></div>
                            <div class="col col-6">
                                <button type="submit" class="btn btn-danger container-fluid">Войти</button>
                            </div>
                        </div>

                    </form>
                </div>
            </div>

        </div>
    </div>

{% endblock %}

main/templates/accounts/login_form.html
{% load home_extras %}
            <form action="/accounts/login/" name="loginform" method="POST" action="" id="loginform">
                {% csrf_token %}

                <div class="form-group row">
                    <label for="id_username" class="col col-4 col-form-label">Телефон</label>
                    <div class="col col-8">
                        <input style="border-radius: 0px" name="username" type="text" class="form-control" id="id_username" placeholder="Номер телефона" value="{{ username }}" required>
                        {% if errors %}
                            {% for i in errors %}
                                <span style="color: red; font-size: 10px">{{ i|gettranslate }}</span>
                            {% endfor %}
                        {% endif %}
                    </div>
                </div>

                <div class="form-group row">
                    <label for="id_password" class="col-sm-4 col-form-label">Пароль</label>
                    <div class="col-sm-8">
                        <input style="border-radius: 0px" name="password" type="password" class="form-control" id="id_password" placeholder="Пароль" value="{{ password1 }}" required>
                    </div>
                </div>

                <div class="form-group row">
                    <div class="col col-6"></div>
                    <div class="col col-6">
                        <button type="submit" class="btn btn-danger container-fluid">Войти</button>
                    </div>
                </div>

            </form>
            <script>

                $(function(){
                  //2. Получить элемент, к которому необходимо добавить маску
                  $("#id_username").mask("8(999) 999-9999");
                });

            </script>

main/templates/accounts/logout.html
{% extends "wrapper.html" %}

{% load i18n %}

{% block head_title %}{% trans "Sign Out" %}{% endblock %}

{% block content %}

<div class="card text-center col-sm-6 container">
  <div class="card-header">
    <h1>{% trans "Выйти" %}</h1>
  </div>
  <div class="card-body">
    <h5 class="card-title">
        <p>{% trans 'Вы уверены, что хотите выйти?' %}</p>
    </h5>

    <form method="post" action="">
      {% csrf_token %}
      {% if redirect_field_value %}
      <input type="hidden" name="{{ redirect_field_name }}" value="{{ redirect_field_value }}"/>
      {% endif %}
      <button type="submit" class="btn btn-danger">{% trans 'Выйти' %}</button>
    </form>

  </div>
</div>

{% endblock %}

main/templates/accounts/password_reset.html
{% extends "wrapper.html" %}

{% load i18n %}
{% load account %}

{% block head_title %}{% trans "Password Reset" %}{% endblock %}

{% block content %}


<div class="card text-center col-sm-6 container">
  <div class="card-header">
        <h1>{% trans "Сбросить пароль" %}</h1>
  </div>
  <div class="card-body">
    <h5 class="card-title">

    </h5>

    <p class="card-text"></p>


    {% if user.is_authenticated %}
    {% include "account/snippets/already_logged_in.html" %}
    {% endif %}

    <p>Забыли пароль? Введите свой адрес электронной почты ниже, и мы отправим вам электронное письмо, которое позволит вам его сбросить.</p>

    <form method="POST" action="{% url 'account_reset_password' %}" class="password_reset">
        {% csrf_token %}
        {{ form.as_p }}
        <input type="submit" class="btn btn-danger" value="{% trans 'Сбросить пароль' %}" />
    </form>

    <p>{% blocktrans %}Если у вас возникли проблемы со сбросом пароля, свяжитесь с нами.{% endblocktrans %}</p>


    </div>
</div>

{% endblock %}

main/templates/accounts/password_reset_done.html
{% extends "wrapper.html" %}

{% load i18n %}
{% load account %}

{% block head_title %}{% trans "Password Reset" %}{% endblock %}

{% block content %}

    <div class="card text-center col-sm-6 container">
      <div class="card-header">
            <h1>{% trans "Пароль сброшен" %}</h1>
      </div>
      <div class="card-body">
        <h5 class="card-title">

        </h5>


        {% if user.is_authenticated %}
        {% include "account/snippets/already_logged_in.html" %}
        {% endif %}

        <p>{% blocktrans %}Мы отправили вам электронное письмо. Пожалуйста, свяжитесь с нами, если вы не получите его в течение нескольких минут.{% endblocktrans %}</p>

      </div>
    </div>
{% endblock %}

main/templates/accounts/password_reset_from_key.html
{% extends "wrapper.html" %}

{% load i18n %}
{% block head_title %}{% trans "Сменить пароль" %}{% endblock %}

{% block content %}

<div class="card text-center col-sm-6 container">
  <div class="card-header">
      <h1>{% if token_fail %}{% trans "Неверный токен" %}{% else %}{% trans "Сменить пароль" %}{% endif %}</h1>
  </div>
  <div class="card-body">
    <h5 class="card-title">

    </h5>

    {% if token_fail %}
        {% url 'account_reset_password' as passwd_reset_url %}
        <p>{% blocktrans %}Ссылка на сброс пароля была недействительной, возможно, потому, что она уже использовалась. Пожалуйста, запросите <a href="{{ passwd_reset_url }}">новый сброс пароля</a>.{% endblocktrans %}</p>
    {% else %}
        {% if form %}
            <form method="POST" action="{{ action_url }}">
                {% csrf_token %}
                {{ form.as_p }}
                <input type="submit" class="btn-danger btn" name="action" value="{% trans 'Сменить пароль' %}"/>
            </form>
        {% else %}
            <p>{% trans 'Your password is now changed.' %}</p>
        {% endif %}
    {% endif %}
  </div>
</div>
{% endblock %}

main/templates/accounts/password_reset_from_key_done.html
{% extends "wrapper.html" %}

{% load i18n %}
{% block head_title %}{% trans "Change Password" %}{% endblock %}

{% block content %}
    <div class="card text-center col-sm-6 container">
  <div class="card-header">
      <h1>{% trans "Пароль изменен" %}</h1>
  </div>
  <div class="card-body">
    <h5 class="card-title">

    </h5>

    <p>{% trans 'Ваш пароль изменен' %}</p>
  </div>
    </div>
{% endblock %}

main/templates/accounts/reset.html
{% extends "wrapper.html" %}
{% load home_extras %}
{% block content %}

<div style="left: 50%; top: 50%; position: absolute; margin: -350px 0 0 -250px;">

    <div class="card" style="width: 500px; border-radius: 0px">
        <div class="card-header text-center">
            <span class="article">Восстановление пароля</span>
        </div>
        <div class="card-body">
            <form action="" method="post" id = "signupform" name="signupform">
                {% csrf_token %}

                <div class="form-group row">
                    <label for="id_username" class="col-sm-4 col-form-label">Телефон</label>
                    <div class="col-sm-8">
                        <input style="border-radius: 0px" name="username" type="text" class="form-control" id="id_username" placeholder="Номер телефона" value="{{ username }}" required {% if confirmphone %} readonly {% endif %}>
                        {% if errors.username %}
                            <span style="color: red; font-size: 10px">{{ errors.username|gettranslate }}</span>
                        {% endif %}
                    </div>
                </div>

                {% if confirmphone %}
                    <div class="form-group row">
                        <label for="id_confirmphone" class="col-sm-4 col-form-label">Код подтверждения</label>
                        <div class="col-sm-8">
                            <input style="border-radius: 0px" name="confirmphone" type="text" class="form-control" id="id_confirmphone" placeholder="Код подтверждения" required>
                            {% if errors.confirmphone %}
                                <span style="color: red; font-size: 10px">{{ errors.confirmphone|gettranslate }}</span>
                            {% endif %}
                        </div>
                    </div>
                {% endif %}

                <div class="form-group row" {% if confirmphone %} hidden {% endif %}>
                    <label for="id_password1" class="col-sm-4 col-form-label">Новый пароль</label>
                    <div class="col-sm-8">
                        <input style="border-radius: 0px" name="password1" type="password" class="form-control" id="id_password1" placeholder="Пароль" value="{{ password1 }}" required>
                        {% if errors.password1 %}
                            <span style="color: red; font-size: 10px">{{ errors.password1|gettranslate }}</span>
                        {% endif %}
                    </div>
                </div>

                <div class="form-group row" {% if confirmphone %} hidden {% endif %}>
                    <label for="id_password2" class="col-sm-4 col-form-label">Повторите пароль</label>
                    <div class="col-sm-8">
                        <input style="border-radius: 0px" name="password2" type="password" class="form-control" id="id_password2" placeholder="Пароль" value="{{ password2 }}" required>
                        {% if errors.password2 %}
                            <span style="color: red; font-size: 10px">{{ errors.password2|gettranslate }}</span>
                        {% endif %}
                    </div>
                </div>

                <div class="form-group row">
                    <div class="col col-6"></div>
                    <div class="col col-6">
                        <button type="submit" class="btn btn-danger container-fluid">Сменить пароль</button>
                    </div>
                </div>
            </form>
        </div>
    </div>

</div>

    <script>

        $(function(){
                      //2. Получить элемент, к которому необходимо добавить маску
                      $("#id_username").mask("8(999) 999-9999");
                    });

        {% if confirmphone %}

        {% endif %}

    </script>

{% endblock %}

main/templates/accounts/signup_closed.html
{% extends "account/base.html" %}

{% load i18n %}

{% block head_title %}{% trans "Sign Up Closed" %}{% endblock %}

{% block content %}
<h1>{% trans "Sign Up Closed" %}</h1>

<p>{% trans "We are sorry, but the sign up is currently closed." %}</p>
{% endblock %}

main/templates/accounts/signup_company.html
{% extends "wrapper.html" %}
{% load home_extras %}
{% block content %}

<div class="container mt-3" style=" width: 500px">

    <div class="card " style="">
        <div class="card-header text-center">
            <span class="article">Регистрация</span>
            <p></p>
            <span class="nav-link">Оставьте заявку на регистрацию, наши менеджеры свяжутся с вами и предоставят доступ к ресурсу</span>
        </div>
        <div class="card-body">
            <form action="" method="post" id = "signupform" name="signupform">
                {% csrf_token %}
                {% if error %}
                    <span style="color: red; font-size: 10px">{{ error }}</span>
                {% endif %}
                <div class="form-group row">
                    <label for="id_name" class="col-sm-4 col-form-label">Имя*</label>
                    <div class="col-sm-8">
                        <input style="border-radius: 0px" name="name" type="text" class="form-control input-sm" id="id_name" placeholder="Название организации" required>
                    </div>
                </div>

                <div class="form-group row">
                    <label for="id_vatnumber" class="col-sm-4 col-form-label">ИНН*</label>
                    <div class="col-sm-8">
                        <input style="border-radius: 0px" name="vatnumber" type="text" class="form-control input-sm" id="id_vatnumber" placeholder="ИНН" required>
                    </div>
                </div>

                <div class="form-group row">
                    <label for="id_username" class="col-sm-4 col-form-label">Телефон*</label>
                    <div class="col-sm-8">
                        <input style="border-radius: 0px" name="username" type="text" class="form-control input-sm" id="id_username" placeholder="Номер телефона" required>
                    </div>
                </div>

                <div class="form-group row">
                    <label for="id_email" class="col-sm-4 col-form-label">Email*</label>
                    <div class="col-sm-8">
                        <input style="border-radius: 0px" name="email" type="text" class="form-control input-sm" id="id_email" placeholder="Электронная почта" required>
                    </div>
                </div>

                <div class="form-group row">
                    <label for="id_description" class="col-sm-4 col-form-label">Описание*</label>
                    <div class="col-sm-8">
                        <input style="border-radius: 0px" name="description" type="text" class="form-control input-sm" id="id_description" placeholder="Краткое описание" required>
                    </div>
                </div>

                <div class="form-group row">
                    <div class="col col-6"></div>
                    <div class="col col-6">
                        <button type="submit" class="btn btn-danger container-fluid">Оставить заявку</button>
                    </div>
                </div>

            </form>
        </div>
    </div>

</div>

    <script>

        $(function(){
          //2. Получить элемент, к которому необходимо добавить маску
          $("#id_username").mask("8(999) 999-9999");
        });
    </script>
{% endblock %}